##################################################################################################
# player service
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
  labels:
    app: player-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: player-service
        version: "1.0"
        serving: "true"
    spec:
      containers:
        - name: player-service
          image: sbishyr/player-service:1.0-slow
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_HOST
              value: redis-service
  selector:
    matchLabels:
      app: player-service
      version: "1.0"
      serving: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: player-service
  labels:
    app: player-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: player-service
    serving: "true"
